package com.cookquest.recipe.integration.impl;

import com.cookquest.battle.dto.RecipePreviewDto;
import com.cookquest.battle.integration.RecipeBattleApi;
import com.cookquest.common.exception.AppException;
import com.cookquest.common.exception.ErrorCode;
import com.cookquest.recipe.entity.Recipe;
import com.cookquest.recipe.repository.RecipeRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class RecipeBattleApiImpl implements RecipeBattleApi {

    private final RecipeRepository recipeRepository;
    private final ObjectMapper objectMapper;

    @Override
    public boolean isRecipeValidForBattle(String recipeId) {
        Recipe recipe = recipeRepository.findById(recipeId).orElse(null);
        if (recipe == null) return false;
        
        // It must have a batchId (meaning it's generated by AI and not a custom user saved one without batch)
        if (recipe.getBatchId() == null) return false;
        
        return true;
    }

    @Override
    public int getBasePoints(String recipeId) {
        return getJsonField(recipeId, "points").asInt(50);
    }

    @Override
    public int getCookingTimeMinutes(String recipeId) {
        return getJsonField(recipeId, "cookingTimeMinutes").asInt(30); // fallback 30
    }

    private JsonNode getJsonField(String recipeId, String fieldName) {
        Recipe recipe = recipeRepository.findById(recipeId)
                .orElseThrow(() -> new AppException(ErrorCode.INVALID_REQUEST, "Рецепт не знайдено", HttpStatus.NOT_FOUND));
        
        try {
            JsonNode root = objectMapper.readTree(recipe.getRecipeJson());
            return root.path(fieldName);
        } catch (Exception e) {
            throw new AppException(ErrorCode.INTERNAL_SERVER_ERROR, "Помилка парсингу рецепта", HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @Override
    public RecipePreviewDto getRecipePreview(String recipeId) {
        Recipe recipeEntity = recipeRepository.findById(recipeId)
                .orElseThrow(() -> new AppException(
                        ErrorCode.NOT_FOUND,
                        "Рецепт з ID " + recipeId + " не знайдено",
                        HttpStatus.NOT_FOUND));

        try {
            JsonNode rootNode = objectMapper.readTree(recipeEntity.getRecipeJson());

            List<String> dietaryTags = objectMapper.convertValue(rootNode.get("dietaryTags"), List.class);
            List<Object> ingredients = objectMapper.convertValue(rootNode.get("ingredients"), List.class);

            return new RecipePreviewDto(
                    recipeId,
                    rootNode.get("name").asText(),
                    rootNode.get("description").asText(),
                    rootNode.get("difficulty").asText(),
                    rootNode.get("points").asInt(),
                    rootNode.get("cookingTimeMinutes").asInt(),
                    rootNode.get("cuisine").asText(),
                    dietaryTags,
                    ingredients,
                    rootNode.get("steps").size()
            );

        } catch (Exception e) {
            throw new AppException(
                    ErrorCode.INTERNAL_SERVER_ERROR,
                    "Не вдалося обробити структуру рецепта",
                    HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
}
