package com.cookquest.common.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    INVALID_PASSWORD,
    BAD_CREDENTIALS,
    PROFILE_NOT_FOUND,

    RECIPE_NOT_FOUND,
    AI_GENERATION_FAILED,
    SECURITY_VIOLATION,
    INVALID_REQUEST,
    AI_VISION_FAILED,
    EXTERNAL_API_ERROR,

    INTERNAL_SERVER_ERROR,
    VALIDATION_ERROR
}