package com.cookquest.common.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    INVALID_PASSWORD,
    BAD_CREDENTIALS,

    RECIPE_NOT_FOUND,
    AI_GENERATION_FAILED,

    INTERNAL_SERVER_ERROR,
    VALIDATION_ERROR
}