spring.application.name=cookquest

# ????? ??????????? ??? ????? -pooler
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ??? ????? ??????? Hibernate, ?? ????????? ? PostgreSQL ??? ?????? ?????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.security.jwt.secret-key=${JWT_SECRET==}
application.security.jwt.expiration=86400000

cloudinary.cloud-name: ${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key: ${CLOUDINARY_API_KEY}
cloudinary.api-secret: ${CLOUDINARY_API_SECRET}


# ===========
#     AI
# ===========

groq.api.key=${GROQ_API_KEY}

groq.model.text=llama-3.3-70b-versatile
groq.model.vision=meta-llama/llama-4-scout-17b-16e-instruct

stability.api.key=${STABILITY_API_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

app.public-url=${PUBLIC_URL}